apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ntdat104/argocd-demo-apps.git' # Thay URL repo GitHub của bạn
    targetRevision: HEAD
    path: '.' # Thư mục chứa file deployment.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
